"""create initial safety schema

Revision ID: 0bf3027fa7ee
Revises:
Create Date: 2026-08-04 13:35:08.172468
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0bf3027fa7ee"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("external_subject", sa.String(length=255), nullable=True),
        sa.Column("phone_masked", sa.String(length=32), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('ELDER', 'GUARDIAN', 'ADMIN')", name=op.f("ck_users_role_values")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("external_subject", name=op.f("uq_users_external_subject")),
    )
    op.create_table(
        "devices",
        sa.Column("external_device_id", sa.String(length=256), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("provider", sa.String(length=32), server_default="ys7", nullable=False),
        sa.Column("status", sa.String(length=20), server_default="UNKNOWN", nullable=False),
        sa.Column("elder_user_id", sa.UUID(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('UNKNOWN', 'ONLINE', 'OFFLINE', 'DISABLED')",
            name=op.f("ck_devices_status_values"),
        ),
        sa.ForeignKeyConstraint(
            ["elder_user_id"],
            ["users.id"],
            name=op.f("fk_devices_elder_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
        sa.UniqueConstraint("external_device_id", name=op.f("uq_devices_external_device_id")),
    )
    op.create_index("ix_devices_elder_user_id", "devices", ["elder_user_id"], unique=False)
    op.create_table(
        "model_runs",
        sa.Column("device_id", sa.UUID(), nullable=True),
        sa.Column("module", sa.String(length=20), nullable=False),
        sa.Column("model_name", sa.String(length=128), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="RUNNING", nullable=False),
        sa.Column(
            "input_refs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "output_summary",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint("module IN ('FRAUD', 'FALL')", name=op.f("ck_model_runs_module_values")),
        sa.CheckConstraint(
            "status IN ('RUNNING', 'SUCCEEDED', 'FAILED')", name=op.f("ck_model_runs_status_values")
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_model_runs_device_id_devices"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_runs")),
    )
    op.create_index(
        "ix_model_runs_device_started", "model_runs", ["device_id", "started_at"], unique=False
    )
    op.create_table(
        "ys7_signal_inbox",
        sa.Column("dedup_key", sa.String(length=512), nullable=False),
        sa.Column("message_id", sa.String(length=256), nullable=True),
        sa.Column("request_id", sa.String(length=256), nullable=True),
        sa.Column("source_event_id", sa.String(length=256), nullable=False),
        sa.Column("external_device_id", sa.String(length=256), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "processing_status", sa.String(length=20), server_default="PENDING", nullable=False
        ),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "processing_status IN ('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED')",
            name=op.f("ck_ys7_signal_inbox_processing_status_values"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_ys7_signal_inbox_device_id_devices"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ys7_signal_inbox")),
        sa.UniqueConstraint("dedup_key", name="uq_ys7_signal_inbox_dedup_key"),
    )
    op.create_index(
        "ix_ys7_signal_inbox_device_occurred",
        "ys7_signal_inbox",
        ["external_device_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_ys7_signal_inbox_status_received",
        "ys7_signal_inbox",
        ["processing_status", "received_at"],
        unique=False,
    )
    op.create_table(
        "risk_events",
        sa.Column("source_event_id", sa.String(length=256), nullable=False),
        sa.Column("external_device_id", sa.String(length=256), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=True),
        sa.Column("model_run_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("risk_level", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="PENDING", nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4, asdecimal=False), nullable=False),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_name", sa.String(length=128), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('FRAUD_SUSPECTED', 'FALL_SUSPECTED')",
            name=op.f("ck_risk_events_event_type_values"),
        ),
        sa.CheckConstraint(
            "risk_level IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')",
            name=op.f("ck_risk_events_risk_level_values"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'CONFIRMED', 'FALSE_ALARM', 'RESOLVED')",
            name=op.f("ck_risk_events_status_values"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_risk_events_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_risk_events_device_id_devices"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["model_run_id"],
            ["model_runs.id"],
            name=op.f("fk_risk_events_model_run_id_model_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_events")),
        sa.UniqueConstraint("source_event_id", name="uq_risk_events_source_event_id"),
    )
    op.create_index(
        "ix_risk_events_device_occurred",
        "risk_events",
        ["external_device_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_risk_events_status_occurred", "risk_events", ["status", "occurred_at"], unique=False
    )
    op.create_table(
        "visual_events",
        sa.Column("source_event_id", sa.String(length=256), nullable=False),
        sa.Column("message_id", sa.String(length=256), nullable=True),
        sa.Column("request_id", sa.String(length=256), nullable=True),
        sa.Column("external_device_id", sa.String(length=256), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=True),
        sa.Column("raw_signal_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4, asdecimal=False), nullable=True),
        sa.Column("people_count", sa.Integer(), nullable=True),
        sa.Column(
            "boxes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "event_type IN ('phone_call', 'people_count', 'person_detected')",
            name=op.f("ck_visual_events_event_type_values"),
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name=op.f("ck_visual_events_confidence_range"),
        ),
        sa.CheckConstraint(
            "people_count IS NULL OR people_count >= 0",
            name=op.f("ck_visual_events_people_count_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_visual_events_device_id_devices"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["raw_signal_id"],
            ["ys7_signal_inbox.id"],
            name=op.f("fk_visual_events_raw_signal_id_ys7_signal_inbox"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_visual_events")),
        sa.UniqueConstraint("raw_signal_id", name=op.f("uq_visual_events_raw_signal_id")),
        sa.UniqueConstraint(
            "source", "source_event_id", name="uq_visual_events_source_source_event_id"
        ),
    )
    op.create_index(
        "ix_visual_events_device_occurred",
        "visual_events",
        ["external_device_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "event_actions",
        sa.Column("risk_event_id", sa.UUID(), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("action_type", sa.String(length=32), nullable=False),
        sa.Column("previous_status", sa.String(length=20), nullable=True),
        sa.Column("new_status", sa.String(length=20), nullable=True),
        sa.Column("note", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "action_type IN ('CONFIRM', 'FALSE_ALARM', 'RESOLVE', 'CONTACT_ELDER', 'NOTE')",
            name=op.f("ck_event_actions_action_type_values"),
        ),
        sa.CheckConstraint(
            "new_status IS NULL OR new_status IN "
            "('PENDING', 'CONFIRMED', 'FALSE_ALARM', 'RESOLVED')",
            name=op.f("ck_event_actions_new_status_values"),
        ),
        sa.CheckConstraint(
            "previous_status IS NULL OR previous_status IN "
            "('PENDING', 'CONFIRMED', 'FALSE_ALARM', 'RESOLVED')",
            name=op.f("ck_event_actions_previous_status_values"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_event_actions_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["risk_event_id"],
            ["risk_events.id"],
            name=op.f("fk_event_actions_risk_event_id_risk_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_actions")),
    )
    op.create_index(
        "ix_event_actions_risk_created",
        "event_actions",
        ["risk_event_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_event_actions_risk_created", table_name="event_actions")
    op.drop_table("event_actions")
    op.drop_index("ix_visual_events_device_occurred", table_name="visual_events")
    op.drop_table("visual_events")
    op.drop_index("ix_risk_events_status_occurred", table_name="risk_events")
    op.drop_index("ix_risk_events_device_occurred", table_name="risk_events")
    op.drop_table("risk_events")
    op.drop_index("ix_ys7_signal_inbox_status_received", table_name="ys7_signal_inbox")
    op.drop_index("ix_ys7_signal_inbox_device_occurred", table_name="ys7_signal_inbox")
    op.drop_table("ys7_signal_inbox")
    op.drop_index("ix_model_runs_device_started", table_name="model_runs")
    op.drop_table("model_runs")
    op.drop_index("ix_devices_elder_user_id", table_name="devices")
    op.drop_table("devices")
    op.drop_table("users")
    # ### end Alembic commands ###
